version: '3.1'
services:
  postgressqldb:
    image: postgres:alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: r2dbc-poc
    volumes:
    - ~/postgres-docker-data:/var/lib/postgresql/data
    networks:
      - r2dbc-poc-internal


networks:
  r2dbc-poc-internal:
